#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
ASTROMANAGER - N.I.N.A. CSV METADATA PARSER
================================================================================
Parses ImageMetaData.csv and WeatherData.csv files generated by N.I.N.A.
(Nighttime Imaging 'N' Astronomy) to extract per-frame quality metrics,
guiding data, focuser state, and environmental conditions.
================================================================================
"""

import csv
import os
import re
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Column name mappings — N.I.N.A. has evolved its CSV format across versions.
# We normalize to canonical names regardless of the exact header spelling.
_IMAGE_META_ALIASES = {
    # HFR variants
    'hfr': 'hfr', 'HFR': 'hfr', 'Hfr': 'hfr',
    'hfr_arcsec': 'hfr', 'HFR (arcsec)': 'hfr',
    # HFR StDev
    'hfrstdev': 'hfr_stdev', 'HFRStDev': 'hfr_stdev',
    'hfr_stdev': 'hfr_stdev', 'HFR StDev': 'hfr_stdev',
    # FWHM
    'fwhm': 'fwhm', 'FWHM': 'fwhm', 'Fwhm': 'fwhm',
    'fwhm_arcsec': 'fwhm', 'FWHM (arcsec)': 'fwhm',
    # Eccentricity
    'eccentricity': 'eccentricity', 'Eccentricity': 'eccentricity',
    # Detected Stars
    'detectedstars': 'detected_stars', 'DetectedStars': 'detected_stars',
    'detected_stars': 'detected_stars', 'Stars': 'detected_stars',
    # Guiding RMS
    'guidingrms': 'guiding_rms_total', 'GuidingRMS': 'guiding_rms_total',
    'guiding_rms': 'guiding_rms_total', 'GuidingRMSArcSec': 'guiding_rms_total',
    'guidingrmsra': 'guiding_rms_ra', 'GuidingRMSRA': 'guiding_rms_ra',
    'guiding_rms_ra': 'guiding_rms_ra', 'GuidingRMSRAArcSec': 'guiding_rms_ra',
    'guidingrmsdec': 'guiding_rms_dec', 'GuidingRMSDEC': 'guiding_rms_dec',
    'guiding_rms_dec': 'guiding_rms_dec', 'GuidingRMSDECArcSec': 'guiding_rms_dec',
    # ADU stats
    'adustdev': 'adu_stdev', 'ADUStDev': 'adu_stdev', 'adu_stdev': 'adu_stdev',
    'adumean': 'adu_mean', 'ADUMean': 'adu_mean', 'adu_mean': 'adu_mean',
    'adumedian': 'adu_median', 'ADUMedian': 'adu_median', 'adu_median': 'adu_median',
    'adumin': 'adu_min', 'ADUMin': 'adu_min',
    'adumax': 'adu_max', 'ADUMax': 'adu_max',
    # Focuser
    'focuserposition': 'focuser_position', 'FocuserPosition': 'focuser_position',
    'focuser_position': 'focuser_position',
    'focusertemp': 'focuser_temp', 'FocuserTemp': 'focuser_temp',
    'focuser_temp': 'focuser_temp', 'FocuserTemperature': 'focuser_temp',
    # Rotator
    'rotatorposition': 'rotator_position', 'RotatorPosition': 'rotator_position',
    'rotator_position': 'rotator_position',
    # Pier side
    'pierside': 'pier_side', 'PierSide': 'pier_side', 'pier_side': 'pier_side',
    # Airmass
    'airmass': 'airmass', 'Airmass': 'airmass',
    # Exposure time
    'exposuretime': 'exposure_seconds', 'ExposureTime': 'exposure_seconds',
    'exposure': 'exposure_seconds', 'Exposure': 'exposure_seconds',
    'duration': 'exposure_seconds', 'Duration': 'exposure_seconds',
    # Filter
    'filter': 'filter_name', 'Filter': 'filter_name', 'FilterName': 'filter_name',
    # Target
    'targetname': 'target_name', 'TargetName': 'target_name',
    'target': 'target_name', 'Target': 'target_name',
    'object': 'target_name', 'Object': 'target_name',
    # Camera
    'camera': 'camera', 'Camera': 'camera', 'CameraName': 'camera',
    # Telescope
    'telescope': 'telescope', 'Telescope': 'telescope', 'TelescopeName': 'telescope',
    # Sensor temperature
    'sensortemp': 'sensor_temp', 'SensorTemp': 'sensor_temp',
    'ccdtemp': 'sensor_temp', 'CCDTemp': 'sensor_temp',
    'temperature': 'sensor_temp', 'Temperature': 'sensor_temp',
    # Gain
    'gain': 'gain', 'Gain': 'gain',
    # Binning
    'binning': 'binning', 'Binning': 'binning',
    # Timestamps
    'exposurestart': 'timestamp', 'ExposureStart': 'timestamp',
    'exposurestartutc': 'timestamp', 'ExposureStartUTC': 'timestamp',
    'date': 'timestamp', 'Date': 'timestamp',
    # File path
    'filepath': 'file_path', 'FilePath': 'file_path',
    'filename': 'file_path', 'FileName': 'file_path',
}

_WEATHER_ALIASES = {
    # Timestamps
    'exposurestartutc': 'timestamp', 'ExposureStartUTC': 'timestamp',
    'date': 'timestamp', 'Date': 'timestamp', 'Time': 'timestamp',
    # Temperature
    'temperature': 'temperature', 'Temperature': 'temperature',
    'ambienttemp': 'temperature', 'AmbientTemp': 'temperature',
    # Dew point
    'dewpoint': 'dewpoint', 'DewPoint': 'dewpoint',
    # Humidity
    'humidity': 'humidity', 'Humidity': 'humidity',
    # Pressure
    'pressure': 'pressure', 'Pressure': 'pressure',
    # Wind
    'windspeed': 'wind_speed', 'WindSpeed': 'wind_speed',
    'winddirection': 'wind_direction', 'WindDirection': 'wind_direction',
    'windgust': 'wind_gust', 'WindGust': 'wind_gust',
    # Cloud
    'cloudcover': 'cloud_cover', 'CloudCover': 'cloud_cover',
    # Sky quality
    'skyquality': 'sky_quality', 'SkyQuality': 'sky_quality',
    'sqm': 'sky_quality', 'SQM': 'sky_quality',
}

# Calibration frame keywords — skip these targets
_CALIBRATION_PATTERNS = {
    'dark', 'flat', 'bias', 'offset', 'flatfield', 'darkframe',
    'biasframe', 'calibration', 'test', 'snapshot',
}

_NUIT_RE = re.compile(r'^(?:Nuit|Night|Session)[_\-]?\d+$', re.IGNORECASE)


def _safe_float(value: str) -> Optional[float]:
    """Safely convert a string to float, returning None on failure."""
    if not value or value.strip() in ('', '-', 'N/A', 'NaN', 'nan', 'null'):
        return None
    try:
        v = float(value.strip())
        if v != v:  # NaN check
            return None
        return v
    except (ValueError, TypeError):
        return None


def _safe_int(value: str) -> Optional[int]:
    """Safely convert a string to int, returning None on failure."""
    f = _safe_float(value)
    if f is None:
        return None
    return int(round(f))


def _parse_timestamp(ts_str: str) -> Optional[str]:
    """Parse various timestamp formats to ISO 8601 string."""
    if not ts_str or not ts_str.strip():
        return None
    ts_str = ts_str.strip()
    # Try common formats
    for fmt in (
        '%Y-%m-%dT%H:%M:%S.%f',
        '%Y-%m-%dT%H:%M:%S',
        '%Y-%m-%d %H:%M:%S.%f',
        '%Y-%m-%d %H:%M:%S',
        '%m/%d/%Y %H:%M:%S',
        '%d/%m/%Y %H:%M:%S',
        '%Y/%m/%d %H:%M:%S',
    ):
        try:
            dt = datetime.strptime(ts_str, fmt)
            return dt.isoformat()
        except ValueError:
            continue
    return ts_str  # Return as-is if no format matches


def _normalize_target_name(name: str) -> str:
    """Normalize catalog target names: 'M31' → 'M 31', 'NGC0224' → 'NGC 224'."""
    if not name:
        return name
    name = ' '.join(name.split())  # collapse whitespace
    # Standard catalogs: add space between prefix and number
    m = re.match(
        r'^(M|NGC|IC|Sh2|SH2|Sh 2|Sh\s*2|LBN|LDN|Ced|Abell|Arp|Barnard|B|C|PGC|UGC|vdB|RCW|Cr|Mel|Tr|Stock)'
        r'[\s\-]*(\d+.*)$', name, re.IGNORECASE)
    if m:
        prefix = m.group(1)
        number = m.group(2).lstrip('0') or '0'
        # Normalize prefix case
        prefix_map = {
            'm': 'M', 'ngc': 'NGC', 'ic': 'IC', 'sh2': 'Sh2', 'sh 2': 'Sh2',
            'lbn': 'LBN', 'ldn': 'LDN', 'ced': 'Ced', 'abell': 'Abell',
            'arp': 'Arp', 'barnard': 'Barnard', 'b': 'B', 'c': 'C',
            'pgc': 'PGC', 'ugc': 'UGC', 'vdb': 'vdB', 'rcw': 'RCW',
            'cr': 'Cr', 'mel': 'Mel', 'tr': 'Tr', 'stock': 'Stock',
        }
        prefix = prefix_map.get(prefix.strip().lower(), prefix)
        sep = '-' if prefix == 'Sh2' else ' '
        return f'{prefix}{sep}{number}'
    return name


def _is_calibration_target(target_name: str) -> bool:
    """Check if target name is a calibration frame."""
    if not target_name:
        return False
    lower = target_name.strip().lower()
    return any(cal in lower for cal in _CALIBRATION_PATTERNS)


def _normalize_columns(headers: List[str], alias_map: dict) -> Dict[str, int]:
    """Map CSV column headers to canonical names using alias map.
    Returns dict: canonical_name -> column_index."""
    mapping = {}
    for idx, raw_header in enumerate(headers):
        # Strip BOM and whitespace
        clean = raw_header.strip().lstrip('\ufeff')
        # Try exact match first
        canonical = alias_map.get(clean)
        if canonical is None:
            # Try case-insensitive match
            lower = clean.lower().replace(' ', '').replace('_', '')
            for alias_key, alias_val in alias_map.items():
                if alias_key.lower().replace(' ', '').replace('_', '') == lower:
                    canonical = alias_val
                    break
        if canonical and canonical not in mapping:
            mapping[canonical] = idx
    return mapping


class NinaCsvParser:
    """Parses N.I.N.A. ImageMetaData.csv and WeatherData.csv files."""

    def __init__(self, skip_calibrations: bool = True):
        self.skip_calibrations = skip_calibrations

    def parse_image_metadata(self, csv_path: str) -> List[Dict]:
        """Parse an ImageMetaData.csv file.

        Returns list of dicts with canonical keys:
        timestamp, target_name, filter_name, exposure_seconds, hfr, fwhm,
        eccentricity, detected_stars, guiding_rms_total/ra/dec, adu_mean/median/stdev,
        focuser_position/temp, airmass, telescope, camera, binning, file_path
        """
        csv_path = str(csv_path)
        if not os.path.isfile(csv_path):
            logger.warning(f"ImageMetaData CSV not found: {csv_path}")
            return []

        results = []
        try:
            # Try utf-8-sig first (handles BOM), fallback to utf-8
            for encoding in ('utf-8-sig', 'utf-8', 'latin-1'):
                try:
                    with open(csv_path, 'r', encoding=encoding, newline='') as f:
                        reader = csv.reader(f)
                        headers = next(reader, None)
                        if headers:
                            break
                except (UnicodeDecodeError, UnicodeError):
                    continue
            else:
                logger.error(f"Cannot decode CSV: {csv_path}")
                return []

            col_map = _normalize_columns(headers, _IMAGE_META_ALIASES)
            if not col_map:
                logger.warning(f"No recognized columns in {csv_path}")
                return []

            def _get(row, key):
                idx = col_map.get(key)
                if idx is not None and idx < len(row):
                    return row[idx]
                return None

            # Re-read with the correct encoding
            with open(csv_path, 'r', encoding=encoding, newline='') as f:
                reader = csv.reader(f)
                next(reader)  # Skip header
                for row_num, row in enumerate(reader, start=2):
                    if not row or all(not cell.strip() for cell in row):
                        continue

                    target = (_get(row, 'target_name') or '').strip()
                    if self.skip_calibrations and _is_calibration_target(target):
                        continue

                    ts_raw = _get(row, 'timestamp')
                    timestamp = _parse_timestamp(ts_raw) if ts_raw else None
                    if not timestamp:
                        continue  # Skip rows without timestamp

                    # Normalize filter names (Hα → Ha, Hβ → Hb, etc.)
                    raw_filter = (_get(row, 'filter_name') or '').strip()
                    _filter_aliases = {'Hα': 'Ha', 'Hβ': 'Hb', 'hα': 'Ha', 'hβ': 'Hb',
                                       'H-Alpha': 'Ha', 'H-Beta': 'Hb', 'H-alpha': 'Ha'}
                    filter_name = _filter_aliases.get(raw_filter, raw_filter) or None

                    entry = {
                        'timestamp': timestamp,
                        'target_name': target or None,
                        'filter_name': filter_name,
                        'exposure_seconds': _safe_float(_get(row, 'exposure_seconds')),
                        'hfr': _safe_float(_get(row, 'hfr')),
                        'hfr_stdev': _safe_float(_get(row, 'hfr_stdev')),
                        'fwhm': _safe_float(_get(row, 'fwhm')),
                        'eccentricity': _safe_float(_get(row, 'eccentricity')),
                        'detected_stars': _safe_int(_get(row, 'detected_stars')),
                        'guiding_rms_total': _safe_float(_get(row, 'guiding_rms_total')),
                        'guiding_rms_ra': _safe_float(_get(row, 'guiding_rms_ra')),
                        'guiding_rms_dec': _safe_float(_get(row, 'guiding_rms_dec')),
                        'adu_mean': _safe_float(_get(row, 'adu_mean')),
                        'adu_median': _safe_float(_get(row, 'adu_median')),
                        'adu_stdev': _safe_float(_get(row, 'adu_stdev')),
                        'focuser_position': _safe_int(_get(row, 'focuser_position')),
                        'focuser_temp': _safe_float(_get(row, 'focuser_temp')),
                        'airmass': _safe_float(_get(row, 'airmass')),
                        'telescope': (_get(row, 'telescope') or '').strip() or None,
                        'camera': (_get(row, 'camera') or '').strip() or None,
                        'sensor_temp': _safe_float(_get(row, 'sensor_temp')),
                        'gain': _safe_int(_get(row, 'gain')),
                        'binning': _safe_int(_get(row, 'binning')),
                        'file_path': (_get(row, 'file_path') or '').strip() or None,
                    }

                    # Derive session_date from timestamp (imaging night = date of evening)
                    try:
                        dt = datetime.fromisoformat(entry['timestamp'])
                        # If before noon, it's the previous night
                        if dt.hour < 12:
                            dt = dt - timedelta(days=1)
                        entry['session_date'] = dt.strftime('%Y-%m-%d')
                    except (ValueError, TypeError):
                        entry['session_date'] = None

                    results.append(entry)

        except Exception as e:
            logger.error(f"Error parsing ImageMetaData CSV {csv_path}: {e}")

        logger.info(f"Parsed {len(results)} exposures from {csv_path}")
        return results

    def parse_weather_data(self, csv_path: str) -> List[Dict]:
        """Parse a WeatherData.csv file.

        Returns list of dicts with canonical keys:
        timestamp, temperature, dewpoint, humidity, pressure,
        wind_speed, wind_direction, wind_gust, cloud_cover, sky_quality
        """
        csv_path = str(csv_path)
        if not os.path.isfile(csv_path):
            logger.warning(f"WeatherData CSV not found: {csv_path}")
            return []

        results = []
        try:
            for encoding in ('utf-8-sig', 'utf-8', 'latin-1'):
                try:
                    with open(csv_path, 'r', encoding=encoding, newline='') as f:
                        reader = csv.reader(f)
                        headers = next(reader, None)
                        if headers:
                            break
                except (UnicodeDecodeError, UnicodeError):
                    continue
            else:
                logger.error(f"Cannot decode CSV: {csv_path}")
                return []

            col_map = _normalize_columns(headers, _WEATHER_ALIASES)
            if not col_map:
                logger.warning(f"No recognized weather columns in {csv_path}")
                return []

            def _get(row, key):
                idx = col_map.get(key)
                if idx is not None and idx < len(row):
                    return row[idx]
                return None

            with open(csv_path, 'r', encoding=encoding, newline='') as f:
                reader = csv.reader(f)
                next(reader)
                for row in reader:
                    if not row or all(not cell.strip() for cell in row):
                        continue

                    ts_raw = _get(row, 'timestamp')
                    timestamp = _parse_timestamp(ts_raw) if ts_raw else None
                    if not timestamp:
                        continue

                    entry = {
                        'timestamp': timestamp,
                        'temperature': _safe_float(_get(row, 'temperature')),
                        'dewpoint': _safe_float(_get(row, 'dewpoint')),
                        'humidity': _safe_float(_get(row, 'humidity')),
                        'pressure': _safe_float(_get(row, 'pressure')),
                        'wind_speed': _safe_float(_get(row, 'wind_speed')),
                        'wind_direction': _safe_float(_get(row, 'wind_direction')),
                        'wind_gust': _safe_float(_get(row, 'wind_gust')),
                        'cloud_cover': _safe_float(_get(row, 'cloud_cover')),
                        'sky_quality': _safe_float(_get(row, 'sky_quality')),
                    }

                    # Derive session_date
                    try:
                        dt = datetime.fromisoformat(entry['timestamp'])
                        if dt.hour < 12:
                            dt = dt - timedelta(days=1)
                        entry['session_date'] = dt.strftime('%Y-%m-%d')
                    except (ValueError, TypeError):
                        entry['session_date'] = None

                    results.append(entry)

        except Exception as e:
            logger.error(f"Error parsing WeatherData CSV {csv_path}: {e}")

        logger.info(f"Parsed {len(results)} weather records from {csv_path}")
        return results

    def join_by_timestamp(self, exposures: List[Dict],
                          weather: List[Dict],
                          tolerance_sec: float = 30.0) -> List[Dict]:
        """Join exposure data with nearest weather data by timestamp.

        For each exposure, finds the closest weather record within tolerance.
        Merges weather fields into the exposure dict (prefixed with 'weather_').
        """
        if not weather:
            return exposures

        # Build sorted list of weather timestamps for binary search
        weather_sorted = sorted(weather, key=lambda w: w.get('timestamp', ''))
        weather_ts = []
        for w in weather_sorted:
            try:
                dt = datetime.fromisoformat(w['timestamp'])
                if dt.tzinfo is not None:
                    dt = dt.replace(tzinfo=None)
                weather_ts.append(dt)
            except (ValueError, TypeError):
                weather_ts.append(None)

        result = []
        for exp in exposures:
            merged = dict(exp)
            try:
                exp_dt = datetime.fromisoformat(exp['timestamp'])
                if exp_dt.tzinfo is not None:
                    exp_dt = exp_dt.replace(tzinfo=None)
            except (ValueError, TypeError):
                result.append(merged)
                continue

            # Binary search for nearest weather record
            best_idx = None
            best_diff = float('inf')
            lo, hi = 0, len(weather_ts) - 1
            while lo <= hi:
                mid = (lo + hi) // 2
                if weather_ts[mid] is None:
                    lo = mid + 1
                    continue
                diff = abs((weather_ts[mid] - exp_dt).total_seconds())
                if diff < best_diff:
                    best_diff = diff
                    best_idx = mid
                if weather_ts[mid] < exp_dt:
                    lo = mid + 1
                else:
                    hi = mid - 1

            # Check neighbors for closer match
            for offset in (-1, 1):
                idx = (best_idx or 0) + offset
                if 0 <= idx < len(weather_ts) and weather_ts[idx] is not None:
                    diff = abs((weather_ts[idx] - exp_dt).total_seconds())
                    if diff < best_diff:
                        best_diff = diff
                        best_idx = idx

            if best_idx is not None and best_diff <= tolerance_sec:
                w = weather_sorted[best_idx]
                for key in ('temperature', 'dewpoint', 'humidity', 'pressure',
                            'wind_speed', 'cloud_cover', 'sky_quality'):
                    if w.get(key) is not None:
                        merged[f'weather_{key}'] = w[key]

            result.append(merged)

        return result

    def scan_folder(self, folder_path: str,
                    progress_callback=None) -> Dict:
        """Scan a folder recursively for N.I.N.A. CSV metadata files.

        Looks for ImageMetaData.csv and WeatherData.csv in each subdirectory.
        Returns summary dict with keys: exposures, weather_records, sessions, errors.
        """
        folder_path = str(folder_path)
        if not os.path.isdir(folder_path):
            return {'exposures': 0, 'weather_records': 0, 'sessions': [], 'errors': [f'Not a directory: {folder_path}']}

        all_exposures = []
        all_weather = []
        sessions = set()
        errors = []

        # Find all CSV files
        csv_pairs = []  # List of (image_csv, weather_csv, folder)
        for dirpath, _dirnames, filenames in os.walk(folder_path):
            lower_files = {f.lower(): f for f in filenames}
            image_csv = None
            weather_csv = None
            for name_lower, name_real in lower_files.items():
                if 'imagemetadata' in name_lower and name_lower.endswith('.csv'):
                    image_csv = os.path.join(dirpath, name_real)
                elif 'weatherdata' in name_lower and name_lower.endswith('.csv'):
                    weather_csv = os.path.join(dirpath, name_real)
            if image_csv:
                csv_pairs.append((image_csv, weather_csv, dirpath))

        total = len(csv_pairs)
        for i, (img_csv, weather_csv, folder) in enumerate(csv_pairs):
            if progress_callback:
                progress_callback(i, total)

            try:
                exposures = self.parse_image_metadata(img_csv)
                weather = []
                if weather_csv:
                    weather = self.parse_weather_data(weather_csv)

                if weather:
                    exposures = self.join_by_timestamp(exposures, weather)

                # Derive target name from folder path if not in CSV
                # N.I.N.A. structures:
                #   .../TargetName/LIGHT/ImageMetaData.csv
                #   .../TargetName/Nuit_N/LIGHT/ImageMetaData.csv
                #   .../Nuit_N/TargetName/LIGHT/ImageMetaData.csv
                folder_target = None
                parts = Path(folder).parts
                for j in range(len(parts) - 1, -1, -1):
                    p = parts[j].upper()
                    if p in ('LIGHT', 'DARK', 'FLAT', 'BIAS', 'DARKFLAT'):
                        # Walk upward max 3 levels, skipping Nuit_N
                        for k in range(j - 1, max(j - 4, -1), -1):
                            candidate = parts[k]
                            # Skip Nuit_N / Night-2 / Session_3 folders
                            if _NUIT_RE.match(candidate):
                                continue
                            # Stop at date-like folders — target should be between date and LIGHT
                            if len(candidate) >= 10 and candidate[4:5] == '-' and candidate[7:8] == '-':
                                break
                            # Stop at observatory root folders
                            if candidate.lower().startswith('observatoire'):
                                break
                            folder_target = candidate
                            break
                        break

                if folder_target:
                    # Normalize whitespace (e.g. "LBN    801" → "LBN 801")
                    folder_target = ' '.join(folder_target.split())

                if folder_target and not _is_calibration_target(folder_target):
                    for exp in exposures:
                        if not exp.get('target_name'):
                            exp['target_name'] = folder_target

                # Fallback: extract target from file_path in CSV
                # NINA pattern: .../TargetName/LIGHT/LIGHT_TargetName_date_...
                for exp in exposures:
                    if not exp.get('target_name') and exp.get('file_path'):
                        fp_parts = Path(exp['file_path']).parts
                        for fi in range(len(fp_parts) - 1, -1, -1):
                            fpu = fp_parts[fi].upper()
                            if fpu in ('LIGHT', 'DARK', 'FLAT', 'BIAS', 'DARKFLAT'):
                                for fk in range(fi - 1, max(fi - 4, -1), -1):
                                    fc = fp_parts[fk]
                                    if _NUIT_RE.match(fc):
                                        continue
                                    if len(fc) >= 10 and fc[4:5] == '-' and fc[7:8] == '-':
                                        break
                                    fc_clean = ' '.join(fc.split())
                                    if not _is_calibration_target(fc_clean):
                                        exp['target_name'] = fc_clean
                                    break
                                break

                # Normalize all target names (M31 → M 31, NGC0224 → NGC 224)
                for exp in exposures:
                    if exp.get('target_name'):
                        exp['target_name'] = _normalize_target_name(exp['target_name'])

                all_exposures.extend(exposures)
                all_weather.extend(weather)

                for exp in exposures:
                    if exp.get('session_date'):
                        sessions.add(exp['session_date'])

            except Exception as e:
                errors.append(f"{folder}: {e}")
                logger.error(f"Error processing {folder}: {e}")

        if progress_callback:
            progress_callback(total, total)

        logger.info(
            f"N.I.N.A. scan complete: {len(all_exposures)} exposures, "
            f"{len(all_weather)} weather records, {len(sessions)} sessions"
        )

        return {
            'exposures': all_exposures,
            'weather_records': all_weather,
            'sessions': sorted(sessions),
            'session_count': len(sessions),
            'exposure_count': len(all_exposures),
            'weather_count': len(all_weather),
            'errors': errors,
        }
